language: bash
sudo: required
dist: trusty

before_script:
    - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar -xvz

before_install:
    - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
    - sudo apt-get -qq update
    - sudo apt-get -t trusty-backports install shellcheck
script:

    - bash src/monitor.sh $Buildparams
    - bash tests/exitstatus.sh
    - bash tests/checkformat.sh
    - shellcheck src/monitor.sh
    - shellcheck src/monitor_np.sh
    - shellcheck tests/checkurl.sh
    - shellcheck tests/exitstatus.sh
